"""Validation guardrails for SQL generated by an LLM.

The most important lesson in this project is that *generation is not enough*. If you let an LLM
write SQL and execute it immediately, you have created a risky system. The model might produce a
query that is destructive, too expensive, or simply invalid. Guardrails are the control layer
between model output and your database.
"""

from __future__ import annotations

import re

import duckdb

FORBIDDEN_KEYWORDS = (
    "insert",
    "update",
    "delete",
    "drop",
    "create",
    "alter",
    "truncate",
    "attach",
    "copy",
    "grant",
    "revoke",
)

# DuckDB table-valued functions that read from the filesystem or network.
# A SELECT query using these passes the read-only keyword check but can still
# expose arbitrary files on the host machine (e.g. SELECT * FROM read_csv_auto('/etc/passwd')).
# We block them explicitly as an additional layer of defence.
FORBIDDEN_FUNCTIONS = (
    "read_csv_auto",
    "read_csv",
    "read_parquet",
    "read_json",
    "read_json_auto",
    "parquet_scan",
    "csv_scan",
    "glob",
    "read_text",
    "read_blob",
    "httpfs",
    "s3",
    "azure",
    "gcs",
)


def is_select_only(sql: str) -> bool:
    """Return True when the query appears to be read-only.

    We validate *before* execution because the database is the expensive, stateful component in
    the pipeline. Once a destructive statement reaches the engine it may be too late. Even if this
    project uses synthetic data, production systems must assume the model can fail in surprising
    ways, so an explicit allow-list / deny-list step is essential.

    We allow queries that start with SELECT or WITH because common table expressions are still
    read-only. Everything else is rejected.

    We also block DuckDB filesystem table-valued functions (read_csv_auto, read_parquet, etc.)
    because they produce valid SELECT-headed SQL that passes the keyword check but can still read
    arbitrary files from the host machine.
    """

    # We normalize case first so the checks behave consistently regardless of model formatting.
    normalized = sql.strip().lower()
    if not normalized.startswith(("select", "with")):
        return False

    for keyword in FORBIDDEN_KEYWORDS:
        if re.search(rf"\b{keyword}\b", normalized):
            return False

    # Block filesystem/network table-valued functions that bypass the keyword check.
    for func in FORBIDDEN_FUNCTIONS:
        if re.search(rf"\b{re.escape(func)}\s*\(", normalized):
            return False

    return True


def has_required_limit(sql: str) -> bool:
    """Return True when the query contains an explicit LIMIT clause.

    LIMIT is a practical cost and safety guardrail. Text-to-SQL systems often sit in front of
    large warehouse tables; without a row cap, a reasonable sounding question could trigger a huge
    scan or return an unreadable wall of data to the user interface.
    """

    return re.search(r"\blimit\s+\d+\b", sql, re.IGNORECASE) is not None


def validate_sql_syntax(sql: str, conn: duckdb.DuckDBPyConnection) -> tuple[bool, str]:
    """Use DuckDB EXPLAIN to catch syntax and binding errors without running the query."""

    try:
        conn.execute(f"EXPLAIN {sql}")
        return True, ""
    except duckdb.Error as exc:
        return False, str(exc)


def run_guardrails(sql: str, conn: duckdb.DuckDBPyConnection) -> tuple[bool, str]:
    """Run every validation check and return the overall decision.

    Each guardrail exists for a different reason:
    - read-only check: prevents destructive or state-changing SQL
    - LIMIT check: keeps result sizes and costs under control
    - syntax check: catches malformed SQL before we try to execute it

    Real systems often add more checks here, such as table allow-lists, column allow-lists,
    regex checks for dangerous functions, query complexity scoring, or a human approval step.
    """

    if not sql.strip():
        return False, "The SQL string is empty."

    if not is_select_only(sql):
        return False, "Guardrail failed: only read-only SELECT statements are allowed."

    if not has_required_limit(sql):
        return False, "Guardrail failed: query must include a LIMIT clause."

    is_valid, error_message = validate_sql_syntax(sql, conn)
    if not is_valid:
        return False, f"Guardrail failed: invalid SQL syntax. {error_message}"

    return True, "SQL passed all guardrails."
